"""Wave 5B-v2: Storage layer entry-point.

Provides the legacy ``storage`` singleton used by existing callers
(``storage.write_bytes(...)``, ``storage.read(...)``, ``storage.delete(...)``)
as a thin shim over the new ``StorageProvider`` abstraction.

All new code should depend on ``get_storage_provider()`` directly.
"""
from __future__ import annotations

import os
from dataclasses import dataclass
from typing import Optional, Tuple

from .providers import get_storage_provider, StoredObject
from .providers.local import MAX_FILE_SIZE_MB, MAX_FILE_SIZE_BYTES

FILE_COLLECTION = "files"

# Legacy MIME whitelist kept identical to the original Wave 5B implementation.
ALLOWED_MIMES = {
    "application/pdf", "application/msword",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "application/vnd.ms-excel",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "text/plain", "text/csv", "application/json",
    "image/jpeg", "image/png", "image/webp", "image/heic", "image/heif", "image/gif",
}


@dataclass
class StoredFile:
    """Back-compat descriptor used by existing callers (router.py, pdf.py).

    ``id`` is generated by the calling layer; the storage provider only
    knows about ``storage_key``. ``path`` is kept as a legacy alias of
    ``storage_key`` so old code that reads ``stored.path`` continues to
    work — it is always treated as a logical key by the provider.
    """
    id: str
    filename: str
    mime: str
    size: int
    path: str  # alias for storage_key (legacy)
    sha256: str
    storage_key: str = ""
    provider: str = "local"

    @classmethod
    def from_stored(cls, *, id: str, obj: StoredObject) -> "StoredFile":
        return cls(
            id=id, filename=obj.filename, mime=obj.mime, size=obj.size,
            path=obj.storage_key, sha256=obj.sha256,
            storage_key=obj.storage_key, provider=obj.provider,
        )

    def to_meta(self):
        return {
            "id": self.id, "filename": self.filename, "mime": self.mime,
            "size": self.size, "sha256": self.sha256,
            "storage_key": self.storage_key, "provider": self.provider,
        }


class _StorageShim:
    """Legacy facade for the old ``LocalStorage`` API.

    Maps the old ``write_bytes/read/delete`` calls onto the active
    StorageProvider. ``id`` is generated here (UUID hex) to preserve the
    old contract; new callers should use FileRepository which manages ids
    explicitly together with versioning.
    """

    def __init__(self) -> None:
        self._provider = get_storage_provider()

    @property
    def provider(self):
        return self._provider

    def write_bytes(self, data: bytes, filename: str, mime: Optional[str] = None, *, generated: bool = False) -> StoredFile:
        import uuid
        if not data:
            raise ValueError("Файл порожній")
        if len(data) > MAX_FILE_SIZE_BYTES:
            raise ValueError(f"Файл перевищує максимум {MAX_FILE_SIZE_MB} МБ")
        from .providers.base import guess_mime
        eff_mime = guess_mime(filename, mime)
        if not generated and eff_mime not in ALLOWED_MIMES:
            raise ValueError(f"Тип «{eff_mime}» не підтримується")
        prefix = "generated" if generated else "uploads"
        obj = self._provider.put_bytes(data, filename=filename, mime=eff_mime, prefix=prefix)
        return StoredFile.from_stored(id=uuid.uuid4().hex, obj=obj)

    def read(self, path: str) -> Tuple[bytes, int]:
        data = self._provider.get_bytes(path)
        return data, len(data)

    def delete(self, path: str) -> None:
        self._provider.delete(path)


# legacy singleton kept for back-compat with router.py / pdf.py imports
storage = _StorageShim()

__all__ = [
    "FILE_COLLECTION", "MAX_FILE_SIZE_MB", "MAX_FILE_SIZE_BYTES",
    "ALLOWED_MIMES", "StoredFile", "storage",
]
