"""
Реальний дата-шар «Національний перелік відходів» (Постанова КМУ № 1102, 20.10.2023).

Завантажує згенерований JSON (`/app/data/national_waste_list.json`) та
експонує:

* CHAPTERS  — 20 глав  (`level=1`)
* GROUPS    — підгрупи (`level=2`)
* CODES     — листові коди (`level=3`)
* CATEGORY_BY_CHAPTER — мапа «глава → бізнес-категорія» для існуючої
  бізнес-логіки (License Matrix / Pricing / Calculator).
* assign_category(code, name, chapter)  — авто-визначення категорії з
  fallback за главою.

Один-єдиний джерело правди для всіх кодів у системі.
"""
from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger("eco.waste.national")

# ─────────────────────────────────────────────────────────────────────────────
#  Source JSON (generated by /app/scripts/parse_national_waste_list.py)
# ─────────────────────────────────────────────────────────────────────────────
_DATA_FILE = Path("/app/data/national_waste_list.json")


def _load() -> List[Dict[str, Any]]:
    if not _DATA_FILE.exists():
        logger.error("National waste list JSON missing: %s", _DATA_FILE)
        return []
    try:
        return json.loads(_DATA_FILE.read_text(encoding="utf-8"))
    except Exception as e:  # pragma: no cover
        logger.exception("Failed to load national waste list: %s", e)
        return []


_ALL_ROWS: List[Dict[str, Any]] = _load()

CHAPTERS: List[Dict[str, Any]] = [r for r in _ALL_ROWS if r.get("level") == 1]
GROUPS: List[Dict[str, Any]] = [r for r in _ALL_ROWS if r.get("level") == 2]
CODES: List[Dict[str, Any]] = [r for r in _ALL_ROWS if r.get("level") == 3]


# ─────────────────────────────────────────────────────────────────────────────
#  Глава -> існуюча бізнес-категорія
#  (Категорії визначені в seed_data.CATEGORIES і керують іконками/іпрайсом)
# ─────────────────────────────────────────────────────────────────────────────
CATEGORY_BY_CHAPTER: Dict[str, str] = {
    "01": "other_hazard",   # Видобування корисних копалин
    "02": "agrochem",       # Сільгосп / харчова промисловість
    "03": "other_hazard",   # Деревина, папір, меблі
    "04": "other_hazard",   # Шкіра, хутро, текстиль
    "05": "oils",           # Нафта, газ, піроліз вугілля
    "06": "agrochem",       # Неорганічна хімія
    "07": "paints",         # Органічна хімія
    "08": "paints",         # Фарби, лаки, клеї
    "09": "other_hazard",   # Фотохімія
    "10": "other_hazard",   # Термічні процеси (шлаки, зола)
    "11": "other_hazard",   # Обробка металів (гальваніка)
    "12": "polymers",       # Формування, механічна обробка
    "13": "oils",           # Нафтопродукти / палива
    "14": "paints",         # Розчинники, холодоагенти
    "15": "plastic",        # Упаковка, сорбенти
    "16": "other_hazard",   # Інші (батареї, електроніка — точкові правила)
    "17": "other_hazard",   # Будівництво/знесення
    "18": "medical",        # Медичні відходи
    "19": "other_hazard",   # Стічні води, обробка відходів
    "20": "organic",        # Побутові відходи (точкові правила)
}

# Точкові правила: «код префікс або повний» -> категорія
CATEGORY_OVERRIDES: List[tuple[str, str]] = [
    # Chapter 13 — Oils
    ("13",       "oils"),
    # Chapter 14 — Solvents
    ("14",       "paints"),
    # Chapter 15 — Packaging/sorbents
    ("15 01",    "plastic"),
    ("15 02",    "oils"),         # promaslene ganchir'ya
    # Chapter 16 — Other (mixed)
    ("16 01",    "tires"),        # шини, авто компоненти
    ("16 02",    "electronics"),  # відпрацьоване обладнання
    ("16 03",    "other_hazard"), # партії, що не відповідають специфікації
    ("16 04",    "other_hazard"), # вибухонебезпечні
    ("16 05",    "agrochem"),     # гази, лабораторні хімікати
    ("16 06",    "batteries"),    # батареї та акумулятори
    ("16 06 01", "accumulators"),
    ("16 06 02", "accumulators"),
    ("16 06 06", "accumulators"),
    ("16 07",    "oils"),         # очистка цистерн
    ("16 08",    "other_hazard"), # відпрацьовані каталізатори
    ("16 09",    "agrochem"),     # окисники
    ("16 10",    "other_hazard"), # водні рідкі відходи
    ("16 11",    "other_hazard"), # відходи футеровки
    # Chapter 17 — Construction
    ("17 06 01", "other_hazard"), # азбест
    ("17 06 05", "other_hazard"), # азбест
    # Chapter 20 — Household
    ("20 01 08", "organic"),
    ("20 01 21", "lamps"),         # ртутні лампи
    ("20 01 23", "lamps"),
    ("20 01 25", "oils"),          # харчові олії
    ("20 01 26", "oils"),
    ("20 01 27", "paints"),
    ("20 01 28", "paints"),
    ("20 01 29", "other_hazard"),
    ("20 01 30", "other_hazard"),
    ("20 01 31", "pharma"),
    ("20 01 32", "pharma"),
    ("20 01 33", "batteries"),
    ("20 01 34", "batteries"),
    ("20 01 35", "electronics"),
    ("20 01 36", "electronics"),
    ("20 01 37", "other_hazard"),
    ("20 01 38", "other_hazard"),
    ("20 01 39", "plastic"),
    ("20 01 40", "other_hazard"),
    ("20 01 41", "other_hazard"),
    ("20 02",    "organic"),
    ("20 03",    "organic"),
]


def _strip_star(code: str) -> str:
    return code.rstrip("*").strip()


def assign_category(code: str, name: str = "", chapter: Optional[str] = None) -> str:
    """Найбільш специфічний overrride -> категорія за главою -> 'other_hazard'."""
    cclean = _strip_star(code)
    # Шукати найдовший префікс-збіг у CATEGORY_OVERRIDES
    best: Optional[tuple[str, str]] = None
    for prefix, cat in CATEGORY_OVERRIDES:
        if cclean.startswith(prefix) and (best is None or len(prefix) > len(best[0])):
            best = (prefix, cat)
    if best:
        return best[1]
    ch = chapter or cclean.split()[0]
    return CATEGORY_BY_CHAPTER.get(ch, "other_hazard")


# ─────────────────────────────────────────────────────────────────────────────
#  Перетворення на «full doc» для колекції waste_codes (тільки листи, level=3)
#  Поле schema сумісне з існуючим build_full_doc через службові ключі.
# ─────────────────────────────────────────────────────────────────────────────
def to_seed_entry(row: Dict[str, Any]) -> Dict[str, Any]:
    """Перетворити рядок national_waste_list.json на seed-запис."""
    code = row["code"]
    cat = assign_category(code, row.get("name", ""), row.get("chapter"))
    return {
        "code": code,
        "name": row["name"],
        "human_names": [],            # буде поповнено адміном
        "category": cat,
        "hazard_class": _default_hazard_class(row),
        "hazardous": bool(row.get("absolute_hazardous")),
        "mirror_hazardous": bool(row.get("mirror_hazardous")),
        # Ієрархія
        "level": row.get("level", 3),
        "chapter": row.get("chapter"),
        "group": row.get("group"),
        "parent_code": row.get("parent_code"),
        # Без price_from — заповнить адмін у Pricing Engine
        "price_from": None,
        # Бути дозволеним за замовч.: рішення приймається License Matrix
        "license_allowed": True,
        "service_available": True,
        # Публічний каталог: увесь офіційний перелік видимий на сайті/в кабінеті.
        # (License Matrix нижче ліцензує кожен код → recompute_accepted_all=True)
        "accepted": True,
        # Maркер «це офіційний код з постанови»
        "source": "national_list_2023",
        "official": True,
    }


def _default_hazard_class(row: Dict[str, Any]) -> Optional[int]:
    """Грубе авто-присвоєння класу небезпеки (1..4)."""
    if not row.get("absolute_hazardous"):
        return None
    chapter = row.get("chapter")
    name_lower = (row.get("name") or "").lower()
    # 1-й клас: ціаніди, цитостатики, ртуть металева, ПХБ
    if any(k in name_lower for k in ["ціанід", "цитостат", "цитотокс", "ртут", "пхб", "поліхлор"]):
        return 1
    # Високий ризик (галерея відходів 06, 18, 02)
    if chapter in ("06", "18", "02"):
        return 2
    return 3


def all_seed_entries() -> List[Dict[str, Any]]:
    """Усі 897 кодів-листів, готових до seeding."""
    return [to_seed_entry(r) for r in CODES]


def all_chapters() -> List[Dict[str, Any]]:
    """20 глав з їхніми ід для UI."""
    return [
        {
            "code": c["code"],
            "name": c["name"],
            "level": 1,
            "category": CATEGORY_BY_CHAPTER.get(c["code"], "other_hazard"),
        }
        for c in CHAPTERS
    ]


def all_groups() -> List[Dict[str, Any]]:
    """115 підгруп."""
    return [
        {
            "code": g["code"],
            "name": g["name"],
            "level": 2,
            "chapter": g.get("chapter"),
            "parent_code": g.get("parent_code"),
        }
        for g in GROUPS
    ]


# ─────────────────────────────────────────────────────────────────────────────
#  ЛІЦЕНЗОВАНИЙ ПЕРЕЛІК — реальні коди, які оператор фактично приймає.
#  Саме цей піднабір керує ПУБЛІЧНОЮ частиною (каталог / категорії / калькулятор /
#  заявка). Решта ~860 кодів лишаються майстер-довідником у адмінці (можна
#  розширити ліцензію в один клік). «Не більше і не менше» — рівно ці коди.
#
#  Джерело номера ліцензії: оператор ECO, ліцензія Мінекології № 1247-ОР.
# ─────────────────────────────────────────────────────────────────────────────
LICENSE_DEFAULTS: Dict[str, Any] = {
    "license_number": "1247-ОР",
    "valid_from": "2020-01-01T00:00:00+00:00",
    "valid_until": "2030-12-31T00:00:00+00:00",
}

# Кожен запис: code + (опц.) hazard_class + людська примітка для адмінки.
LICENSED_CODES: List[Dict[str, Any]] = [
    # ── Відпрацьовані оливи та нафтопродукти (глава 13) ──
    {"code": "13 02 05*", "notes": "Відпрацьовані мінеральні моторні, трансмісійні та мастильні оливи"},
    {"code": "13 02 06*", "notes": "Синтетичні моторні, трансмісійні та мастильні оливи"},
    {"code": "13 02 08*", "notes": "Інші моторні, індустріальні та мастильні оливи"},
    {"code": "13 01 10*", "notes": "Мінеральні гідравлічні нехлоровані оливи"},
    {"code": "13 01 13*", "notes": "Інші гідравлічні оливи"},
    {"code": "13 05 02*", "notes": "Шлами масло-водовідокремлювачів (сепараторів)"},
    {"code": "13 07 01*", "notes": "Газойль, котельне та дизельне паливо"},
    # ── Тара, сорбенти, фільтри (глава 15) ──
    {"code": "15 01 10*", "notes": "Упаковка із залишками небезпечних речовин"},
    {"code": "15 02 02*", "notes": "Промаслені сорбенти, фільтрувальні матеріали, ганчір'я, спецодяг"},
    # ── Шини, фільтри, авторідини (глава 16.01) ──
    {"code": "16 01 03", "notes": "Відпрацьовані шини"},
    {"code": "16 01 07*", "notes": "Масляні фільтри"},
    {"code": "16 01 13*", "notes": "Гальмівні рідини"},
    {"code": "16 01 14*", "notes": "Антифризні рідини з небезпечними речовинами"},
    # ── Електронне обладнання / ВЕЕО (глава 16.02 + 20.01) ──
    {"code": "16 02 11*", "notes": "Зношене обладнання, що містить хлорофторовуглеці"},
    {"code": "16 02 13*", "notes": "Відходи обладнання з небезпечними компонентами"},
    {"code": "20 01 35*", "notes": "Відходи електричного та електронного обладнання (ВЕЕО)"},
    # ── Батареї та акумулятори (глава 16.06 + 20.01) ──
    {"code": "16 06 01*", "notes": "Свинцеві акумулятори"},
    {"code": "16 06 02*", "notes": "Нікелево-кадмієві батареї"},
    {"code": "16 06 04", "notes": "Лужні батареї"},
    {"code": "20 01 33*", "notes": "Батареї та акумулятори у складі змішаних відходів"},
    # ── Ртутьвмісні відходи / лампи (глава 20.01 + 06) ──
    {"code": "20 01 21*", "notes": "Люмінесцентні лампи та інші ртутьвмісні відходи"},
    {"code": "20 01 23*", "notes": "Обладнання, що містить хлорофторовуглеці"},
    {"code": "06 04 04*", "notes": "Відходи, що містять ртуть"},
    # ── Фарби, лаки, розчинники, чорнила (глави 08, 14) ──
    {"code": "08 01 11*", "notes": "Відходи фарб і лаків з органічними розчинниками"},
    {"code": "08 03 17*", "notes": "Відходи друкарських фарб (чорнил) з небезпечними речовинами"},
    {"code": "14 06 03*", "notes": "Інші розчинники та суміші розчинників"},
    {"code": "09 01 01*", "notes": "Проявники і розчини активаторів на водній основі"},
    # ── Медичні та фармацевтичні відходи (глава 18) ──
    {"code": "18 01 03*", "notes": "Інфіковані медичні відходи (спецвимоги до збирання)"},
    {"code": "18 01 08*", "notes": "Цитотоксичні та цитостатичні лікарські препарати"},
    {"code": "18 01 09", "notes": "Лікарські препарати (нецитотоксичні)"},
    {"code": "20 01 31*", "notes": "Цитотоксичні та цитостатичні медикаменти (побутові)"},
    # ── Харчові олії та жири (глава 20.01) ──
    {"code": "20 01 25", "notes": "Харчові олії та жири"},
    {"code": "20 01 26*", "notes": "Олії та жири з небезпечними домішками"},
    # ── Лабораторні хімікати, азбест (глави 16.05, 17.06) ──
    {"code": "16 05 06*", "notes": "Лабораторні хімікати з небезпечних речовин"},
    {"code": "17 06 05*", "notes": "Будівельні матеріали, що містять азбест"},
]

# Примітки з куратора (де є) — щоб License Matrix мала людський опис.
_CURATED_NOTES: Dict[str, str] = {c["code"]: c.get("notes", "") for c in LICENSED_CODES}

# Швидкий сет кодів для перевірок acceptance = УВЕСЬ офіційний перелік.
LICENSED_CODE_SET = {r["code"] for r in CODES}


def licensed_seed_entries() -> List[Dict[str, Any]]:
    """Записи для колекції waste_license_matrix (allowed=True, з валідністю).

    ПОЛІТИКА (2026): оператор ліцензує та публічно показує УВЕСЬ офіційний
    «Національний перелік відходів». Тобто кожен код-лист (level=3) стає
    ``accepted=True`` (публічний каталог/сайт/кабінет). Адмін може згодом
    вимкнути окремі коди через License Matrix.
    """
    out: List[Dict[str, Any]] = []
    for row in CODES:
        code = row["code"]
        out.append({
            "waste_code": code,
            "allowed": True,
            "license_number": LICENSE_DEFAULTS["license_number"],
            "valid_from": LICENSE_DEFAULTS["valid_from"],
            "valid_until": LICENSE_DEFAULTS["valid_until"],
            "notes": _CURATED_NOTES.get(code) or row.get("name"),
            "source": "license_seed",
        })
    return out


# ─────────────────────────────────────────────────────────────────────────────
#  Стат для діагностики
# ─────────────────────────────────────────────────────────────────────────────
def stats() -> Dict[str, int]:
    return {
        "chapters": len(CHAPTERS),
        "groups": len(GROUPS),
        "codes": len(CODES),
        "hazardous": sum(1 for r in CODES if r.get("absolute_hazardous")),
        "mirror": sum(1 for r in CODES if r.get("mirror_hazardous")),
    }
