"""
SEO router (ECO.NOVA) — centralized, production-grade SEO surfaces.

Everything is generated by the backend/app/seo/ engine package so the site
stays consistent and free of legacy BiBi Cars artifacts:

  GET /api/seo/robots.txt            env-aware robots
  GET /api/seo/sitemap.xml           sitemap INDEX
  GET /api/seo/sitemap-pages.xml     static public pages (+hreflang)
  GET /api/seo/sitemap-catalog.xml   waste categories + codes
  GET /api/seo/sitemap-blog.xml      published articles
  GET /api/seo/sitemap-images.xml    image sitemap
  GET /api/seo/meta                  per-route metadata + JSON-LD (frontend)
  GET /api/seo/runtime-config        public analytics/verification config
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional

from fastapi import APIRouter, Request, Response, Query

from app.seo import get_origin, canonical_url, hreflang_alternates
from app.seo import robots as robots_engine
from app.seo import sitemap as sm
from app.seo import schema as S
from app.seo import metadata as M
from app.seo import config as seo_config

router = APIRouter(prefix="/api/seo", tags=["seo"])

_XML = "application/xml"


def _db(request: Request):
    st = getattr(request.app, "state", None)
    return getattr(st, "db", None) if st is not None else None


async def _company(request: Request) -> Dict[str, Any]:
    """Assemble company facts for JSON-LD, ADMIN-FIRST.

    Primary source: admin-managed seo_settings (via the SEO config cache).
    Footer contacts fill any gaps. Never fabricates: unknown fields stay
    empty so schema.py omits them.
    """
    db = _db(request)
    await seo_config.load(db)
    company: Dict[str, Any] = seo_config.company()
    # Footer / contacts as a fallback for anything the admin hasn't set yet.
    try:
        from settings_service import get_settings_service  # type: ignore
        footer = await get_settings_service().get_footer()
        contacts = (footer or {}).get("contacts", {})
        comp = (footer or {}).get("company", {})
        fb_phones = contacts.get("phones") or ([contacts.get("phone")] if contacts.get("phone") else [])
        if not company.get("legal_name"):
            company["legal_name"] = comp.get("legalName")
        if not company.get("edrpou"):
            company["edrpou"] = comp.get("edrpou")
        if not company.get("phones"):
            company["phones"] = [p for p in fb_phones if p]
            company["phone"] = (company["phones"] or [None])[0]
        if not company.get("email"):
            company["email"] = contacts.get("email")
        if not company.get("street"):
            company["street"] = contacts.get("address")
        if not company.get("opening_hours"):
            company["opening_hours"] = contacts.get("working_hours")
    except Exception:
        pass
    return company


# ─────────────────────────────────────────────────────────────── robots ──
@router.get("/robots.txt", response_class=Response)
async def robots_txt(request: Request) -> Response:
    await seo_config.load(_db(request))
    return Response(
        content=robots_engine.build_robots(request),
        media_type="text/plain",
        headers={"Cache-Control": "public, max-age=3600"},
    )


# ────────────────────────────────────────────────────────────── sitemaps ──
@router.get("/sitemap.xml", response_class=Response)
async def sitemap_index(request: Request) -> Response:
    await seo_config.load(_db(request))
    return Response(content=sm.sitemap_index(request), media_type=_XML,
                    headers={"Cache-Control": "public, max-age=3600"})


@router.get("/sitemap-pages.xml", response_class=Response)
async def sitemap_pages(request: Request) -> Response:
    await seo_config.load(_db(request))
    return Response(content=sm.sitemap_pages(request), media_type=_XML,
                    headers={"Cache-Control": "public, max-age=3600"})


@router.get("/sitemap-catalog.xml", response_class=Response)
async def sitemap_catalog(request: Request) -> Response:
    await seo_config.load(_db(request))
    xml = await sm.sitemap_catalog(_db(request), request)
    return Response(content=xml, media_type=_XML,
                    headers={"Cache-Control": "public, max-age=1800"})


@router.get("/sitemap-blog.xml", response_class=Response)
async def sitemap_blog(request: Request) -> Response:
    xml = await sm.sitemap_blog(_db(request), request)
    return Response(content=xml, media_type=_XML,
                    headers={"Cache-Control": "public, max-age=1800"})


@router.get("/sitemap-images.xml", response_class=Response)
async def sitemap_images(request: Request) -> Response:
    xml = await sm.sitemap_images(_db(request), request)
    return Response(content=xml, media_type=_XML,
                    headers={"Cache-Control": "public, max-age=3600"})


@router.get("/sitemap-content.xml", response_class=Response)
async def sitemap_content(request: Request) -> Response:
    """Phase D1: CMS-published pages (services / industries / landings / custom)."""
    xml = await sm.sitemap_content(_db(request), request)
    return Response(content=xml, media_type=_XML,
                    headers={"Cache-Control": "public, max-age=1800"})


# ─────────────────────────────────────────────── per-route metadata + LD ──
async def resolve_page_meta(request: Request, path: str = "/", lang: str = "uk") -> Dict[str, Any]:
    """Compute the meta+JSON-LD dict for `path`/`lang`.

    Extracted from `route_meta` so both the public HTTP endpoint AND the
    prerender engine can share exactly the same resolution logic (there
    must be zero drift between what the SPA renders and what bots see)."""
    lang = "en" if (lang or "").lower().startswith("en") else "uk"
    db = _db(request)
    await seo_config.load(db)
    origin = get_origin(request)
    path = path or "/"
    if len(path) > 1 and path.endswith("/"):
        path = path.rstrip("/")

    # Base metadata: static registry, else dynamic resolvers.
    base = M.resolve_static(path, lang, origin)
    extra_nodes: List[Dict[str, Any]] = []
    published = updated = author = image = None

    if base is None:
        # ---- dynamic: /waste/category/{key} ----
        if path.startswith("/waste/category/"):
            key = path.rsplit("/", 1)[-1]
            label = key.replace("-", " ").replace("_", " ").title()
            try:
                if db is not None:
                    doc = await db.waste_codes.find_one({"category": key}, {"_id": 0, "category": 1})
                    if doc:
                        label = key.replace("_", " ").title()
            except Exception:
                pass
            t = (f"Відходи: {label}" if lang == "uk" else f"Waste: {label}")
            d = (f"Коди та вимоги до поводження з відходами категорії «{label}» за національним класифікатором."
                 if lang == "uk"
                 else f"Codes and handling requirements for the “{label}” waste category under the national classifier.")
            base = {"title": t, "full_title": f"{t} · {M.TITLE_SUFFIX[lang]}",
                    "description": d, "keywords": "", "type": "website",
                    "is_app": False, "lang": lang,
                    "breadcrumbs": [
                        {"name": "Головна" if lang == "uk" else "Home", "url": f"{origin}/"},
                        {"name": "Каталог" if lang == "uk" else "Catalog", "url": f"{origin}/waste"},
                        {"name": label, "url": f"{origin}{path}"},
                    ]}
        # ---- dynamic: /waste-code/{slug} ----
        elif path.startswith("/waste-code/"):
            slug = path.rsplit("/", 1)[-1]
            code = slug.replace("-", " ")
            try:
                if db is not None:
                    doc = await db.waste_codes.find_one({"slug": slug}, {"_id": 0, "code": 1, "updated_at": 1})
                    if doc:
                        code = doc.get("code") or code
                        updated = doc.get("updated_at")
            except Exception:
                pass
            t = (f"Код відходу {code}" if lang == "uk" else f"Waste code {code}")
            d = (f"Код {code} за національним класифікатором відходів: клас небезпеки, вимоги до пакування, "
                 f"транспортування та методи утилізації."
                 if lang == "uk"
                 else f"Code {code} under the national waste classifier: hazard class, packaging, transport and utilization methods.")
            base = {"title": t, "full_title": f"{t} · {M.TITLE_SUFFIX[lang]}",
                    "description": d, "keywords": code, "type": "website",
                    "is_app": False, "lang": lang,
                    "breadcrumbs": [
                        {"name": "Головна" if lang == "uk" else "Home", "url": f"{origin}/"},
                        {"name": "Каталог" if lang == "uk" else "Catalog", "url": f"{origin}/waste"},
                        {"name": code, "url": f"{origin}{path}"},
                    ]}
        # ---- dynamic: /blog/{slug} ----
        elif path.startswith("/blog/"):
            slug = path.rsplit("/", 1)[-1]
            t = slug.replace("-", " ").capitalize()
            d = ""
            try:
                if db is not None:
                    doc = await db.blog_articles.find_one({"slug": slug}, {"_id": 0}) or {}
                    t = doc.get("title") or t
                    d = doc.get("excerpt") or doc.get("summary") or doc.get("description") or ""
                    image = doc.get("cover_image") or doc.get("image")
                    published = doc.get("published_at") or doc.get("created_at")
                    updated = doc.get("updated_at")
                    author = (doc.get("author") or {}).get("name") if isinstance(doc.get("author"), dict) else doc.get("author")
            except Exception:
                pass
            base = {"title": t, "full_title": f"{t} · {M.TITLE_SUFFIX[lang]}",
                    "description": d, "keywords": "", "type": "article",
                    "is_app": False, "lang": lang,
                    "breadcrumbs": [
                        {"name": "Головна" if lang == "uk" else "Home", "url": f"{origin}/"},
                        {"name": "Блог" if lang == "uk" else "Blog", "url": f"{origin}/blog"},
                        {"name": t, "url": f"{origin}{path}"},
                    ]}
        else:
            # Unknown public path → generic homepage-like metadata (still valid).
            base = M.resolve_static("/", lang, origin)

    canonical = canonical_url(f"{path}?lang=en" if lang == "en" else path, request)
    alternates = hreflang_alternates(path, request)

    # ---- Admin per-route override (OG/Twitter/canonical/robots) ----
    admin_over: Dict[str, Any] = base.get("override") or {}
    if admin_over.get("canonical_override"):
        canonical = admin_over["canonical_override"]
    robots_value = admin_over.get("robots_override") or "index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1"

    # ---- JSON-LD @graph ----
    company = await _company(request)
    url = f"{origin}{path}" if path != "/" else f"{origin}/"
    nodes: List[Dict[str, Any]] = [
        S.organization(company, origin),
        S.website(origin),
        S.web_page(origin, canonical, base["title"], base["description"], lang,
                   published=published, updated=updated,
                   breadcrumb_id=f"{canonical}#breadcrumb"),
    ]
    # Admin breadcrumbs override (if provided)
    admin_crumbs = admin_over.get("breadcrumbs") if isinstance(admin_over, dict) else None
    if admin_crumbs:
        nodes.append(S.breadcrumb_list(admin_crumbs, canonical))
    elif base.get("breadcrumbs"):
        nodes.append(S.breadcrumb_list(base["breadcrumbs"], canonical))
    if path == "/":
        nodes.append(S.local_business(company, origin))
    if base.get("is_app"):
        nodes.append(S.software_application(
            origin, canonical, base["title"], base["description"]))
    if base.get("type") == "article":
        nodes.append(S.article(origin, canonical, base["title"], base["description"],
                               image, published, updated, author, lang))
    # Admin FAQ block → FAQPage schema
    faq = admin_over.get("faq") if isinstance(admin_over, dict) else None
    if faq and isinstance(faq, list):
        try:
            nodes.append({
                "@type": "FAQPage",
                "@id": f"{canonical}#faq",
                "mainEntity": [
                    {"@type": "Question",
                     "name": row.get("q") or "",
                     "acceptedAnswer": {"@type": "Answer", "text": row.get("a") or ""}}
                    for row in faq if isinstance(row, dict)
                ],
            })
        except Exception:
            pass
    nodes.extend(extra_nodes)
    jsonld = S.graph(nodes)

    # Prefer admin OG image, then per-blog image, then company logo, then favicon.
    og_image = (
        admin_over.get("og_image")
        or image
        or company.get("logo")
        or (f"{origin}/android-chrome-512x512.png" if origin else "")
    )
    og_title       = admin_over.get("og_title") or base["title"]
    og_description = admin_over.get("og_description") or base["description"]
    tw_title       = admin_over.get("twitter_title") or base["title"]
    tw_description = admin_over.get("twitter_description") or base["description"]

    return {
        "path": path,
        "lang": lang,
        "title": base["full_title"],
        "shortTitle": base["title"],
        "description": base["description"],
        "keywords": base.get("keywords", ""),
        "canonical": canonical,
        "robots": robots_value,
        "hreflang": alternates,
        "og": {
            "type": base.get("type", "website"),
            "site_name": "ECO.NOVA",
            "title": og_title,
            "description": og_description,
            "url": canonical,
            "image": og_image,
            "locale": "uk_UA" if lang == "uk" else "en_US",
            "locale_alternate": "en_US" if lang == "uk" else "uk_UA",
        },
        "twitter": {
            "card": "summary_large_image",
            "title": tw_title,
            "description": tw_description,
            "image": og_image,
        },
        "breadcrumbs": admin_crumbs or base.get("breadcrumbs", []),
        "published": published,
        "updated": updated,
        "author": author,
        "jsonld": jsonld,
        # Extras only the prerender uses:
        "_faq": faq or [],
        "_admin_override": admin_over,
    }


@router.get("/meta")
async def route_meta(
    request: Request,
    path: str = Query("/", description="Public route path, e.g. /waste"),
    lang: str = Query("uk"),
) -> Dict[str, Any]:
    """Return everything the frontend <SeoHead> needs for a given route."""
    return await resolve_page_meta(request, path=path, lang=lang)


# (Legacy inline body follows — replaced by resolve_page_meta above.) Kept
# as-is behind a dead-code guard to preserve line stability during Phase C.
async def _legacy_route_meta(
    request: Request,
    path: str = "/",
    lang: str = "uk",
) -> Dict[str, Any]:
    """Return everything the frontend <SeoHead> needs for a given route."""
    lang = "en" if (lang or "").lower().startswith("en") else "uk"
    db = _db(request)
    await seo_config.load(db)
    origin = get_origin(request)
    path = path or "/"
    if len(path) > 1 and path.endswith("/"):
        path = path.rstrip("/")

    # Base metadata: static registry, else dynamic resolvers.
    base = M.resolve_static(path, lang, origin)
    extra_nodes: List[Dict[str, Any]] = []
    published = updated = author = image = None

    if base is None:
        # ---- dynamic: /waste/category/{key} ----
        if path.startswith("/waste/category/"):
            key = path.rsplit("/", 1)[-1]
            label = key.replace("-", " ").replace("_", " ").title()
            try:
                if db is not None:
                    doc = await db.waste_codes.find_one({"category": key}, {"_id": 0, "category": 1})
                    if doc:
                        label = key.replace("_", " ").title()
            except Exception:
                pass
            t = (f"Відходи: {label}" if lang == "uk" else f"Waste: {label}")
            d = (f"Коди та вимоги до поводження з відходами категорії «{label}» за національним класифікатором."
                 if lang == "uk"
                 else f"Codes and handling requirements for the “{label}” waste category under the national classifier.")
            base = {"title": t, "full_title": f"{t} · {M.TITLE_SUFFIX[lang]}",
                    "description": d, "keywords": "", "type": "website",
                    "is_app": False, "lang": lang,
                    "breadcrumbs": [
                        {"name": "Головна" if lang == "uk" else "Home", "url": f"{origin}/"},
                        {"name": "Каталог" if lang == "uk" else "Catalog", "url": f"{origin}/waste"},
                        {"name": label, "url": f"{origin}{path}"},
                    ]}
        # ---- dynamic: /waste-code/{slug} ----
        elif path.startswith("/waste-code/"):
            slug = path.rsplit("/", 1)[-1]
            code = slug.replace("-", " ")
            try:
                if db is not None:
                    doc = await db.waste_codes.find_one({"slug": slug}, {"_id": 0, "code": 1, "updated_at": 1})
                    if doc:
                        code = doc.get("code") or code
                        updated = doc.get("updated_at")
            except Exception:
                pass
            t = (f"Код відходу {code}" if lang == "uk" else f"Waste code {code}")
            d = (f"Код {code} за національним класифікатором відходів: клас небезпеки, вимоги до пакування, "
                 f"транспортування та методи утилізації."
                 if lang == "uk"
                 else f"Code {code} under the national waste classifier: hazard class, packaging, transport and utilization methods.")
            base = {"title": t, "full_title": f"{t} · {M.TITLE_SUFFIX[lang]}",
                    "description": d, "keywords": code, "type": "website",
                    "is_app": False, "lang": lang,
                    "breadcrumbs": [
                        {"name": "Головна" if lang == "uk" else "Home", "url": f"{origin}/"},
                        {"name": "Каталог" if lang == "uk" else "Catalog", "url": f"{origin}/waste"},
                        {"name": code, "url": f"{origin}{path}"},
                    ]}
        # ---- dynamic: /blog/{slug} ----
        elif path.startswith("/blog/"):
            slug = path.rsplit("/", 1)[-1]
            t = slug.replace("-", " ").capitalize()
            d = ""
            try:
                if db is not None:
                    doc = await db.blog_articles.find_one({"slug": slug}, {"_id": 0}) or {}
                    t = doc.get("title") or t
                    d = doc.get("excerpt") or doc.get("summary") or doc.get("description") or ""
                    image = doc.get("cover_image") or doc.get("image")
                    published = doc.get("published_at") or doc.get("created_at")
                    updated = doc.get("updated_at")
                    author = (doc.get("author") or {}).get("name") if isinstance(doc.get("author"), dict) else doc.get("author")
            except Exception:
                pass
            base = {"title": t, "full_title": f"{t} · {M.TITLE_SUFFIX[lang]}",
                    "description": d, "keywords": "", "type": "article",
                    "is_app": False, "lang": lang,
                    "breadcrumbs": [
                        {"name": "Головна" if lang == "uk" else "Home", "url": f"{origin}/"},
                        {"name": "Блог" if lang == "uk" else "Blog", "url": f"{origin}/blog"},
                        {"name": t, "url": f"{origin}{path}"},
                    ]}
        else:
            # Unknown public path → generic homepage-like metadata (still valid).
            base = M.resolve_static("/", lang, origin)

    canonical = canonical_url(f"{path}?lang=en" if lang == "en" else path, request)
    alternates = hreflang_alternates(path, request)

    # ---- Admin per-route override (OG/Twitter/canonical/robots) ----
    admin_over: Dict[str, Any] = base.get("override") or {}
    if admin_over.get("canonical_override"):
        canonical = admin_over["canonical_override"]
    robots_value = admin_over.get("robots_override") or "index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1"

    # ---- JSON-LD @graph ----
    company = await _company(request)
    url = f"{origin}{path}" if path != "/" else f"{origin}/"
    nodes: List[Dict[str, Any]] = [
        S.organization(company, origin),
        S.website(origin),
        S.web_page(origin, canonical, base["title"], base["description"], lang,
                   published=published, updated=updated,
                   breadcrumb_id=f"{canonical}#breadcrumb"),
    ]
    # Admin breadcrumbs override (if provided)
    admin_crumbs = admin_over.get("breadcrumbs") if isinstance(admin_over, dict) else None
    if admin_crumbs:
        nodes.append(S.breadcrumb_list(admin_crumbs, canonical))
    elif base.get("breadcrumbs"):
        nodes.append(S.breadcrumb_list(base["breadcrumbs"], canonical))
    if path == "/":
        nodes.append(S.local_business(company, origin))
    if base.get("is_app"):
        nodes.append(S.software_application(
            origin, canonical, base["title"], base["description"]))
    if base.get("type") == "article":
        nodes.append(S.article(origin, canonical, base["title"], base["description"],
                               image, published, updated, author, lang))
    # Admin FAQ block → FAQPage schema
    faq = admin_over.get("faq") if isinstance(admin_over, dict) else None
    if faq and isinstance(faq, list):
        try:
            nodes.append({
                "@type": "FAQPage",
                "@id": f"{canonical}#faq",
                "mainEntity": [
                    {"@type": "Question",
                     "name": row.get("q") or "",
                     "acceptedAnswer": {"@type": "Answer", "text": row.get("a") or ""}}
                    for row in faq if isinstance(row, dict)
                ],
            })
        except Exception:
            pass
    nodes.extend(extra_nodes)
    jsonld = S.graph(nodes)

    # Prefer admin OG image, then per-blog image, then company logo, then favicon.
    og_image = (
        admin_over.get("og_image")
        or image
        or company.get("logo")
        or (f"{origin}/android-chrome-512x512.png" if origin else "")
    )
    og_title       = admin_over.get("og_title") or base["title"]
    og_description = admin_over.get("og_description") or base["description"]
    tw_title       = admin_over.get("twitter_title") or base["title"]
    tw_description = admin_over.get("twitter_description") or base["description"]

    return {
        "path": path,
        "lang": lang,
        "title": base["full_title"],
        "shortTitle": base["title"],
        "description": base["description"],
        "keywords": base.get("keywords", ""),
        "canonical": canonical,
        "robots": robots_value,
        "hreflang": alternates,
        "og": {
            "type": base.get("type", "website"),
            "site_name": "ECO.NOVA",
            "title": og_title,
            "description": og_description,
            "url": canonical,
            "image": og_image,
            "locale": "uk_UA" if lang == "uk" else "en_US",
            "locale_alternate": "en_US" if lang == "uk" else "uk_UA",
        },
        "twitter": {
            "card": "summary_large_image",
            "title": tw_title,
            "description": tw_description,
            "image": og_image,
        },
        "breadcrumbs": admin_crumbs or base.get("breadcrumbs", []),
        "published": published,
        "updated": updated,
        "author": author,
        "jsonld": jsonld,
    }


# ─────────────────────────────────────────────────────── runtime config ──
@router.get("/runtime-config")
async def runtime_config(request: Request) -> Dict[str, Any]:
    db = _db(request)
    doc: Dict[str, Any] = {}
    if db is not None:
        try:
            doc = await db.seo_settings.find_one({"_id": "global"}) or {}
        except Exception:
            doc = {}
    return {
        "ga4_measurement_id":       doc.get("ga4_measurement_id") or "",
        "gtm_container_id":         doc.get("gtm_container_id") or "",
        "google_ads_conversion_id": doc.get("google_ads_conversion_id") or "",
        "google_ads_send_page_view": bool(doc.get("google_ads_send_page_view", True)),
        "google_ads_conversion_labels": doc.get("google_ads_conversion_labels") or {},
        "facebook_pixel_id":        doc.get("facebook_pixel_id") or "",
        "linkedin_insight_id":      doc.get("linkedin_insight_id") or "",
        "google_site_verification": doc.get("google_site_verification") or "",
        "bing_site_verification":   doc.get("bing_site_verification") or "",
        "yandex_site_verification": doc.get("yandex_site_verification") or "",
        "indexnow_key":             doc.get("indexnow_key") or "",
        "default_title":       doc.get("default_title") or "",
        "default_description": doc.get("default_description") or "",
        "default_keywords":    doc.get("default_keywords") or "",
        "default_og_image":    doc.get("default_og_image") or "",
        "site_name":           doc.get("site_name") or "ECO.NOVA",
        "default_language":    doc.get("default_language") or "uk",
        "enabled_languages":   doc.get("enabled_languages") or "uk,en",
    }


__all__ = ["router"]
