/**
 * Client cabinet bilingual copy (UA + EN only).
 *
 * The /client/* cabinet is part of the customer-facing product, so it must be
 * fully translatable. Staff/admin/manager back-office stays Ukrainian-only.
 *
 * Usage:
 *   const { lang, L, stageLabel } = useClientCopy();
 *   <h1>{L.overviewH}</h1>
 *   <span>{stageLabel(r.stage, r.stage_label)}</span>
 */
import { useLang } from '@/i18n';

export const STAGE_LABELS = {
  uk: {
    new: 'Нова', quote: 'Прорахунок', contract: 'Договір', pickup: 'Вивіз',
    utilization: 'Утилізація', act: 'Акт готовий', archived: 'Архів',
  },
  en: {
    new: 'New', quote: 'Quote', contract: 'Contract', pickup: 'Pickup',
    utilization: 'Utilization', act: 'Act ready', archived: 'Archived',
  },
};

export const CLIENT_COPY = {
  uk: {
    // generic
    loading: 'Завантаження…',
    none: 'Немає',
    kg: 'кг',
    menu: 'Меню',
    close: 'Закрити',
    remove: 'Прибрати',
    // layout / nav
    navOverview: 'Огляд',
    navRequests: 'Заявки',
    navInvoices: 'Рахунки',
    navDocuments: 'Документи',
    navProfile: 'Профіль',
    navMessages: 'Повідомлення',
    messagesH: 'Повідомлення',
    msgEyebrow: 'Від команди ECO',
    msgEmpty: 'Поки немає повідомлень',
    markAllRead: 'Прочитати всі',
    logout: 'Вихід',
    // overview
    ovEyebrow: 'Особистий профіль',
    overviewH: 'Огляд',
    newRequest: '+ Нова заявка',
    kpiTotal: 'Всього заявок',
    kpiActive: 'Активні',
    kpiCompleted: 'Завершені',
    kpiAmount: 'Сума договорів',
    managerEyebrow: 'Ваш персональний менеджер',
    recentH: 'Останні заявки',
    allRequests: 'Усі заявки →',
    ovEmpty: 'Ще немає заявок. Створіть першу — це займе хвилину.',
    createRequest: 'Створити заявку',
    // requests list
    reqEyebrow: 'Замовлення',
    requestsH: 'Мої заявки',
    reqEmpty: 'У вас ще немає заявок.',
    createFirst: 'Створити першу заявку',
    thNumDate: '№ / Дата',
    thItems: 'Позиції',
    thStatus: 'Статус',
    thAmount: 'Сума',
    repeat: 'Повторити',
    // documents
    docEyebrow: 'Архів',
    documentsH: 'Документи',
    docEmpty: "Договорів та актів поки немає. Вони з'являться тут після оформлення замовлення.",
    contracts: 'Договори',
    actsH: 'Акти утилізації',
    tagContract: 'Договір',
    tagAct: 'Акт',
    // profile
    profEyebrow: 'Акаунт',
    profileH: 'Профіль',
    fEmail: 'Email',
    fName: "Ім'я / контактна особа",
    fPhone: 'Телефон',
    fCompany: 'Компанія / заклад',
    fPosition: 'Посада',
    saving: 'Збереження…',
    save: 'Зберегти',
    saved: 'Збережено ✓',
    signOut: 'Вийти з акаунта',
    // request detail
    backAll: '← Усі заявки',
    backToRequests: '← До заявок',
    requestWord: 'Заявка',
    repeatOrder: 'Повторити замовлення',
    itemsH: 'Позиції',
    hazardous: 'небезпечний',
    amountLbl: 'Сума:',
    tbc: 'уточнюється',
    weightLbl: 'Вага:',
    timelineH: 'Хронологія',
    noEvents: 'Поки що без подій',
    detailDocsEmpty: "Документи з'являться після підготовки договору та акта.",
    errNoAccess: 'Немає доступу до цієї заявки',
    errNotFound: 'Заявку не знайдено',
    // new request modal
    nrEyebrow: 'ECO · Самообслуговування',
    nrTitle: 'Нова заявка на утилізацію',
    nrSub: 'Знайдіть коди відходів (приймаємо лише ліцензовані), вкажіть масу — і ми підготуємо прорахунок.',
    nrSearchPh: 'Пошук коду або назви (напр. 18 01 03 або акумулятори)…',
    nrSearching: 'Пошук…',
    nrComment: 'Коментар',
    nrErrEmpty: 'Додайте хоча б один код відходу',
    nrErrCreate: 'Не вдалося створити заявку',
    nrCreating: 'Створення…',
    nrCreate: 'Створити заявку',
    // reset password
    rpEyebrow: 'Відновлення доступу',
    rpTitle: 'Новий пароль',
    rpChecking: 'Перевіряємо посилання…',
    rpInvalid: 'Посилання недійсне або застаріле. Запросіть нове на сторінці входу.',
    rpToLogin: 'До сторінки входу',
    rpCreateFor: (e) => <>Створення нового паролю для <b>{e}</b>.</>,
    rpCreateGeneric: 'Створіть новий надійний пароль для вашого акаунта.',
    rpNewPass: 'Новий пароль',
    rpRepeat: 'Повторіть пароль',
    rpSaveLogin: 'Зберегти та увійти',
    rpBackLogin: '← До сторінки входу',
    rpErrWeak: 'Пароль має містити щонайменше 8 символів і відповідати вимогам нижче.',
    rpErrMismatch: 'Паролі не співпадають.',
    rpErrFail: 'Не вдалося оновити пароль. Посилання могло застаріти.',
  },
  en: {
    loading: 'Loading…',
    none: 'None',
    kg: 'kg',
    menu: 'Menu',
    close: 'Close',
    remove: 'Remove',
    navOverview: 'Overview',
    navRequests: 'Requests',
    navInvoices: 'Invoices',
    navDocuments: 'Documents',
    navProfile: 'Profile',
    navMessages: 'Messages',
    messagesH: 'Messages',
    msgEyebrow: 'From the ECO team',
    msgEmpty: 'No messages yet',
    markAllRead: 'Mark all read',
    logout: 'Sign out',
    ovEyebrow: 'Personal profile',
    overviewH: 'Overview',
    newRequest: '+ New request',
    kpiTotal: 'Total requests',
    kpiActive: 'Active',
    kpiCompleted: 'Completed',
    kpiAmount: 'Contracts total',
    managerEyebrow: 'Your personal manager',
    recentH: 'Recent requests',
    allRequests: 'All requests →',
    ovEmpty: 'No requests yet. Create your first — it takes a minute.',
    createRequest: 'Create request',
    reqEyebrow: 'Orders',
    requestsH: 'My requests',
    reqEmpty: "You don't have any requests yet.",
    createFirst: 'Create your first request',
    thNumDate: 'No. / Date',
    thItems: 'Items',
    thStatus: 'Status',
    thAmount: 'Amount',
    repeat: 'Repeat',
    docEyebrow: 'Archive',
    documentsH: 'Documents',
    docEmpty: 'No contracts or acts yet. They will appear here after your order is processed.',
    contracts: 'Contracts',
    actsH: 'Utilization acts',
    tagContract: 'Contract',
    tagAct: 'Act',
    profEyebrow: 'Account',
    profileH: 'Profile',
    fEmail: 'Email',
    fName: 'Name / contact person',
    fPhone: 'Phone',
    fCompany: 'Company / institution',
    fPosition: 'Position',
    saving: 'Saving…',
    save: 'Save',
    saved: 'Saved ✓',
    signOut: 'Sign out',
    backAll: '← All requests',
    backToRequests: '← Back to requests',
    requestWord: 'Request',
    repeatOrder: 'Repeat order',
    itemsH: 'Items',
    hazardous: 'hazardous',
    amountLbl: 'Amount:',
    tbc: 'to be confirmed',
    weightLbl: 'Weight:',
    timelineH: 'Timeline',
    noEvents: 'No events yet',
    detailDocsEmpty: 'Documents will appear after the contract and act are prepared.',
    errNoAccess: 'No access to this request',
    errNotFound: 'Request not found',
    nrEyebrow: 'ECO · Self-service',
    nrTitle: 'New utilization request',
    nrSub: 'Find waste codes (we accept licensed ones only), set the weight — and we will prepare a quote.',
    nrSearchPh: 'Search code or name (e.g. 18 01 03 or batteries)…',
    nrSearching: 'Searching…',
    nrComment: 'Comment',
    nrErrEmpty: 'Add at least one waste code',
    nrErrCreate: 'Could not create the request',
    nrCreating: 'Creating…',
    nrCreate: 'Create request',
    rpEyebrow: 'Access recovery',
    rpTitle: 'New password',
    rpChecking: 'Verifying the link…',
    rpInvalid: 'The link is invalid or expired. Request a new one on the sign-in page.',
    rpToLogin: 'Go to sign-in',
    rpCreateFor: (e) => <>Create a new password for <b>{e}</b>.</>,
    rpCreateGeneric: 'Create a new strong password for your account.',
    rpNewPass: 'New password',
    rpRepeat: 'Repeat password',
    rpSaveLogin: 'Save and sign in',
    rpBackLogin: '← Back to sign-in',
    rpErrWeak: 'The password must be at least 8 characters and meet the requirements below.',
    rpErrMismatch: 'Passwords do not match.',
    rpErrFail: 'Could not update the password. The link may have expired.',
  },
};

export function useClientCopy() {
  const { lang } = useLang();
  const code = lang === 'en' ? 'en' : 'uk';
  const L = CLIENT_COPY[code];
  const stageLabel = (stage, fallback) =>
    (STAGE_LABELS[code] && STAGE_LABELS[code][stage]) || fallback || stage || '';
  return { lang: code, L, stageLabel };
}

export default useClientCopy;
